# Generated by Django 2.1.2 on 2018-12-14 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.FileField(upload_to='projects')),
                ('Nombre', models.CharField(max_length=50)),
                ('Fecha', models.DateField()),
                ('Edad', models.IntegerField()),
                ('Direccion', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=8)),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='registroascensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCliente', models.CharField(max_length=40)),
                ('FechaInicio', models.DateField()),
                ('HoraInicio', models.CharField(max_length=5)),
                ('HoraTermino', models.CharField(max_length=5)),
                ('ModeloAscensor', models.CharField(max_length=70)),
                ('FallasAscensor', models.CharField(max_length=70)),
                ('ReparacionesEfectuadas', models.CharField(max_length=70)),
                ('PiezasCambiadas', models.CharField(max_length=70)),
                ('NombreTrabajadorAsignado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='registrocliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCliente', models.CharField(max_length=40)),
                ('DireccionCliente', models.CharField(max_length=60)),
                ('CiudadCliente', models.CharField(max_length=60)),
                ('ComunaCliente', models.CharField(max_length=60)),
                ('TelefonoCliente', models.CharField(max_length=9)),
                ('CorreoCliente', models.CharField(max_length=40)),
                ('EstadoCliente', models.CharField(choices=[('Atendido', 'Atendido'), ('No Atendido', 'No Atendido'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado')], default='Atendido', max_length=40)),
                ('AsignadoCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
